{
    "openapi": "3.0.3",
    "info": {
        "title": "Typescript Express Starter Swagger API Documentation",
        "version": "0.0.1"
    },
    "servers": [
        {
            "url": "http://localhost:5000"
        }
    ],
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "schemas": {
            "User": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "format": "email"
                    },
                    "_id": {
                        "type": "string"
                    },
                    "createdAt": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updatedAt": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "__v": {
                        "type": "number"
                    }
                }
            },
            "Token": {
                "type": "string"
            }
        }
    },
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/": {
            "get": {
                "tags": [
                    "index"
                ],
                "summary": "Get an acknowledgment that the server is up and running",
                "operationId": "indexGet",
                "responses": {
                    "204": {
                        "description": "Ok - No Content"
                    }
                }
            }
        },
        "/authentication/signup": {
            "post": {
                "tags": [
                    "authentication",
                    "signup",
                    "post"
                ],
                "summary": "Create a new account on the platform using an email and a password",
                "operationId": "authenticationSignupPost",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "format": "email"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "confirmationPassword": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "email": "john@thedoes.com",
                                "password": "myPassword",
                                "confirmationPassword": "myPassword"
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Validation Error"
                    },
                    "404": {
                        "description": "Email already exists"
                    },
                    "500": {
                        "description": "Something went wrong"
                    },
                    "200": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "user": {
                                            "$ref": "#/components/schemas/User"
                                        },
                                        "jwtToken": {
                                            "$ref": "#/components/schemas/Token"
                                        },
                                        "refreshToken": {
                                            "$ref": "#/components/schemas/Token"
                                        }
                                    }
                                },
                                "example": {
                                    "user": {
                                        "email": "email@email.com",
                                        "_id": "64eb8007ee20aa2d70569a58",
                                        "createdAt": "2023-08-27T16:55:35.750Z",
                                        "updatedAt": "2023-08-27T16:55:35.750Z",
                                        "__v": 0
                                    },
                                    "jwtToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
                                    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/authentication/signin": {
            "post": {
                "tags": [
                    "authentication",
                    "signin",
                    "post"
                ],
                "summary": "Signin to an already existing account on the platform using an email and a password",
                "operationId": "authenticationSigninPost",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "format": "email"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "email": "john@thedoes.com",
                                "password": "myPassword"
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Validation Error"
                    },
                    "500": {
                        "description": "Something went wrong"
                    },
                    "200": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "user": {
                                            "$ref": "#/components/schemas/User"
                                        },
                                        "jwtToken": {
                                            "$ref": "#/components/schemas/Token"
                                        },
                                        "refreshToken": {
                                            "$ref": "#/components/schemas/Token"
                                        }
                                    }
                                },
                                "example": {
                                    "user": {
                                        "email": "email@email.com",
                                        "_id": "64eb8007ee20aa2d70569a58",
                                        "createdAt": "2023-08-27T16:55:35.750Z",
                                        "updatedAt": "2023-08-27T16:55:35.750Z",
                                        "__v": 0
                                    },
                                    "jwtToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
                                    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/authentication/signout": {
            "get": {
                "tags": [
                    "authentication",
                    "signout",
                    "post"
                ],
                "summary": "Signout of an already existing account on the platform using a refreshToken",
                "operationId": "authenticationSignoutGet",
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Something went wrong"
                    },
                    "204": {
                        "description": "Ok - No Content"
                    }
                }
            }
        },
        "/authentication/refresh": {
            "post": {
                "tags": [
                    "authentication",
                    "refresh",
                    "post"
                ],
                "summary": "Get a new jwtToken when the old jwtToken is expired or lost using the refreshToken for an existing account on the platform",
                "operationId": "authenticationRefreshPost",
                "parameters": [
                    {
                        "in": "header",
                        "name": "refreshToken",
                        "type": "string",
                        "description": "The refreshToken for an existing account on the platform"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Something went wrong"
                    },
                    "200": {
                        "description": "Ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "user": {
                                            "$ref": "#/components/schemas/User"
                                        },
                                        "jwtToken": {
                                            "$ref": "#/components/schemas/Token"
                                        },
                                        "refreshToken": {
                                            "$ref": "#/components/schemas/Token"
                                        }
                                    }
                                },
                                "example": {
                                    "user": {
                                        "email": "email@email.com",
                                        "_id": "64eb8007ee20aa2d70569a58",
                                        "createdAt": "2023-08-27T16:55:35.750Z",
                                        "updatedAt": "2023-08-27T16:55:35.750Z",
                                        "__v": 0
                                    },
                                    "jwtToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
                                    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}